Repository retaildevcrews/helium-java, pull requests merged in 2020-06, with the labels that each got.

#252 Resolving Sonar Linter Messages from VSCode
  src/main/java/com/cse/helium/app/Constants.java
  src/main/java/com/cse/helium/app/config/BuildConfig.java
  src/main/java/com/cse/helium/app/config/CosmosDbConfig.java
  src/main/java/com/cse/helium/app/controllers/ActorsController.java
  src/main/java/com/cse/helium/app/controllers/Controller.java
  src/main/java/com/cse/helium/app/controllers/FeaturedController.java
  src/main/java/com/cse/helium/app/controllers/GenresController.java
  src/main/java/com/cse/helium/app/controllers/HealthzController.java
  src/main/java/com/cse/helium/app/controllers/IndexController.java
  src/main/java/com/cse/helium/app/controllers/MoviesController.java
  src/main/java/com/cse/helium/app/controllers/RobotsController.java
  src/main/java/com/cse/helium/app/dao/ActorsDao.java
  src/main/java/com/cse/helium/app/dao/BaseCosmosDbDao.java
  src/main/java/com/cse/helium/app/dao/FeaturedMovieDao.java
  src/main/java/com/cse/helium/app/dao/GenresDao.java
  src/main/java/com/cse/helium/app/dao/IDao.java
  src/main/java/com/cse/helium/app/dao/MoviesDao.java
  src/main/java/com/cse/helium/app/error/HeliumException.java
  src/main/java/com/cse/helium/app/health/ietf/IeTfStatus.java
  src/main/java/com/cse/helium/app/models/Actor.java
  src/main/java/com/cse/helium/app/models/ActorBase.java
  src/main/java/com/cse/helium/app/models/Entity.java
  src/main/java/com/cse/helium/app/models/FeaturedMovie.java
  src/main/java/com/cse/helium/app/models/Genre.java
  src/main/java/com/cse/helium/app/models/Movie.java
  src/main/java/com/cse/helium/app/models/MovieBase.java
  src/main/java/com/cse/helium/app/models/Role.java
  src/main/java/com/cse/helium/app/services/configuration/ConfigurationService.java
  src/main/java/com/cse/helium/app/services/keyvault/EnvironmentReader.java
  src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
  src/main/java/com/cse/helium/app/utils/CommonUtils.java
  src/main/java/com/cse/helium/app/utils/ParameterValidator.java
Labels: Bug, Java, Pri1

#258 cicd readme updates
  README.md
Labels: Java, Pri1

#256 perfTargets.json to .txt
  TestFiles/perfTargets.json
  TestFiles/perfTargets.txt
Labels: Java, Pri1

#260 Updated ci-cd
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.yml
  .github/workflows/open-issues-triage.yml
  .github/workflows/open-pr-submitted.yml
Labels: Java

#261 remove perfTargets.json once we have merged webV changes please
  TestFiles/perfTargets.json
Labels: Java

#262 added vscode template
  docs/vscode-template/launch.json
  docs/vscode-template/tasks.json
Labels: Java

#264 Jofultz kv log
  src/main/java/com/cse/helium/app/HeliumJavaApplication.java
  src/main/java/com/cse/helium/app/services/keyvault/KeyVaultSecretsLogPolicy.java
  src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
  src/main/resources/log4j2.properties
  src/main/resources/logback.xml
Labels: Java, Pri1, size: L

#267 Identity SDK Update
  pom.xml
  src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
Labels: Java, Pri1

#269 removing mvn clean package and moving env up in launch.json
  README.md
  docs/vscode-template/launch.json
  pom.xml
Labels: Java, Pri1, size: S

#272 added ietf error msg to readme
  README.md
Labels: Java, Pri1, size: S

#274 added TestFiles to ignore
  .github/workflows/dockerCI.yml
Labels: Java

#273 added bash completion to install script
  .devcontainer/post-install.sh
Labels: Java
