Repository retaildevcrews/helium-java, pull requests merged in 2020-09, with the labels that each got.

#310 Added link checker to CI, updated dead links
  .github/ISSUE_TEMPLATE/user-story.md
  .github/workflows/mdlinkcheck.yml
  README.md
  mlc_config.json
Labels: Bug, Documentation

#311 add language to /version
  TestFiles/baseline.json
  src/main/java/com/cse/helium/app/controllers/VersionController.java
Labels: Java

#312 Added scheduled checks to CI
  .github/ISSUE_TEMPLATE/found-dead-links.md
  .github/workflows/mdlinkcheck.yml
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, Documentation

#316 Use custom helium banner
  src/main/resources/application.properties
  src/main/resources/static/startup-banner.txt
Labels: Java

#315 Package and SDK version updates
  pom.xml
Labels: Java

#317 Sync root docs with other Helium repos
  README.md
  SECURITY.md
Labels: Documentation, Java

#319 Updated scheduled link check to create project cards
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, CI/CD, Documentation

#321 Scheduled push for devcontainer image
  .github/workflows/codespaces.yml
Labels: CustomerFeedback, Java
