Repository retaildevcrews/helium-java, pull requests merged in 2020-10, with the labels that each got.

#324 Java docker environment for codespaces
  .devcontainer/.bashrc-append
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/azcli-debian.sh
  .devcontainer/library-scripts/docker-debian.sh
  .devcontainer/library-scripts/node-debian.sh
  .devcontainer/post-install.sh
Labels: CustomerFeedback, Java

#327 Update deprecated set-env commands for actions to new syntax
  .github/workflows/codespaces.yml
  .github/workflows/dockerCI.yml
Labels: CI/CD

#330 Fixing 400 error resp link headers and update test files
  TestFiles/bad.json
  TestFiles/baseline.json
  TestFiles/e2e.json
  src/main/java/com/cse/helium/app/utils/InvalidParameterResponses.java
Labels: Java
