Repository retaildevcrews/helium-java, pull requests merged in 2020-02, with the labels that each got.

#42 Updated cosmosdb creation command
  README.md
Labels: Java, Pri1

#56 syncing issue template from helium
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/designreview.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/retro.md
  .github/ISSUE_TEMPLATE/survey.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: Documentation, Java

#76 Java -Design Template update
  .github/ISSUE_TEMPLATE/designreview.md
Labels: Bug, Documentation, Pri1

#74 renamed workflow files to .tmp to pause CI until ready
  .github/workflows/dockerByPR.tmp
  .github/workflows/dockerCI.tmp
Labels: Java, Pri1, size: S

#79 Create Dockerfile
  Dockerfile
Labels: Enhancement, Java, Pri1, size: S

#84 Jofultz mikv
  .gitignore
  pom.xml
  src/main/java/com/microsoft/cse/helium/app/config/BuildConfig.java
  src/main/java/com/microsoft/cse/helium/app/config/SwaggerConfig.java
  src/main/java/com/microsoft/cse/helium/app/controllers/SecretController.java
  src/main/java/com/microsoft/cse/helium/app/services/keyvault/IKeyVaultService.java
  src/main/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultService.java
  src/main/resources/application.properties
  src/test/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultServiceTest.java
Labels: Java

#85 Updated Standard Templates (Bug, Task, Release, DoD, Feature)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/task.md
Labels: Documentation, Java, Pri1

#86 Updated Standard Templates (DoD, Feature)
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: Documentation, Java, Pri1

#87 update ignore paths to ignore all changes to .md files instead of README
  .github/workflows/dockerByPR.tmp
  .github/workflows/dockerCI.tmp
Labels: Bug, Java, Pri1, size: S

#89 Refactor to mono
  src/main/java/com/microsoft/cse/helium/app/controllers/SecretController.java
  src/main/java/com/microsoft/cse/helium/app/services/keyvault/IKeyVaultService.java
  src/main/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultService.java
  src/test/java/com/microsoft/cse/helium/app/controllers/VersionControllerTest.java
Labels: Bug, Java, size: S
